import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';

export default function Application() {

    const randomNum = Math.floor(Math.random() * (99999 - 10000));
    const [randomNumber, setRandomNumber] = useState(0);

    useEffect(() => {
        setRandomNumber(randomNum);
    }, []); // add empty dependency 

    return (
        <>

            <div>
                <h1>Application</h1>
                <div id="container">
                    
                    <form action="" method="get" onSubmit={handleSubmit}>
                        <div class="section" name="student-id" key={randomNumber}>
                            <div>Autogenerated Student ID:</div>
                            <div>{randomNumber}</div>
                        </div>

                        <div class="section">
                            <label for="status">Status: </label>
                            <select>
                                <option value=""></option>
                                <option value="pending">Pending</option>
                                <option value="approved">Approved</option>
                                <option value="denied">Denied</option>
                            </select>
                        </div>

                        <div class="section">
                            <label for="cost">Enter the application cost: </label>
                            <div>
                               $<input type="text" name="cost" id="cost" required /> 
                            </div>
                        </div>
                        <button type='submit'>Submit</button>
                    </form>
                </div>
                
                <div class="flex">
                    <Link href='/'>Home</Link>
                    <Link href='/dorm'>Next: Dorm</Link>
                </div>
                
            </div>

        
        </>
    )
}